### ISSUE TITLE
Requesting to add podspec for protobuf-c 1.3

### ISSUE THREAD

**Issue by naveenkumart28** [maxsz/protobuf-c#3]
Hello Maxi,
        Could you please add an updated podpsec for protobuf-c 1.3. So that i can be integrated in  https://cocoapods.org/pods/protobuf-c ? This could be really helpful as protobuf-c 1.3 comes with Google protobuf 3.x, which has various issues fixed.

**Comment by maxsz** [comment]
Sure, just send a pull request.
